### ISSUE TITLE
Color for the top bar in unity

### ISSUE THREAD

**Issue by Michael-A-D** [eti1337/arc-grey-theme#1]
For some reason, the top satusbar was displayed in the original arc-theme blueish color in unity. Is that expected? I expected the whole theme to use greyish colors.

Anyway, I locally solved that in the latest revision with a global (and brutal) `sed -i "s/2f343f/373737/g"` on the whole sources, since I did not expect to have the blueish "2f343f" anywhere.

Shall this be pushed?

**Comment by eti0** [comment]
I don't see why it shouldn't, I'll push this to the dev branch

**Comment by Michael-A-D** [comment]
Sweet, I guess this can be clised then.

Thanks for your time!

**Comment by eti0** [comment]
Hey, that might be weird to ask, but did you execute the command on the Unity part of the theme or just on the GTK's folders ?

Edit: Nevermind, I just found out how to use sed.

**Comment by Michael-A-D** [comment]
Hey, I did on the whole folder, I wanted the change to be global. But the attribute that matters for me was indeed in the unity part.

**Comment by eti0** [comment]
Okay, no problem.
Seems like it was fixed anyway.
