### ISSUE TITLE
XFCE4-Panel Themed Incorrectly

### ISSUE THREAD

**Issue by mirrornoir** [eti1337/arc-grey-theme#13]
xfce4-panel is still themed like Arc instead of Arc Grey. You can see the difference in this screenshot. This theme is absolutely perfect otherwise. Keep up the good work!

![2017-01-17-160349_1366x768_scrot](https://cloud.githubusercontent.com/assets/19215655/22039834/d1e9ae52-dcce-11e6-9049-502f447b3027.png)

**Comment by eti0** [comment]
Just checked and there are no files that contain any non-grey values in the common/xfwm4 folder.
Maybe the panel's colors are located elsewhere.
I'm going to try finding if some values are defined the gtk.css files.

Edit:
Actually there are some in the common/gtk-2.0/panel.rc.
I'll push an update when I'm done changing these.

**Comment by eti0** [comment]
Fixed with ee8ba05d6a280932dbe8f90932e8266e8bd67a14.

**Comment by mirrornoir** [comment]
Thanks, so much. I have never seen one of my bug reports responded to and fixed so quickly, you rock!
