### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by ddnexus** [eti1337/arc-grey-theme#15]
In the Arc Theme (and grey variants) the default Gnome Shell app icon (in the top panel) is missing. How could I add it back?

**Comment by eti0** [comment]
Could you please be more specific?
I don't seem to have this issue though I am not sure what you are talking about.

**Comment by ddnexus** [comment]
I mean the application icon that is usually displayed on the left of the active application name in the top bar panel. E.g. when you have a Nautilus window in focus the top bar would be: 

`Activities <Nautilus App Icon> Files ...`

The whatever App Icon is never displayed in Arc variants.

**Comment by eti0** [comment]
Oh well, it's not supposed to be displayed anyway.
I personally don't like these icons and prefer having them removed, and since the menu still works I don't see any issue.

Closing this ticket because it's related to the original theme and not to my fork.

**Comment by ddnexus** [comment]
Indeed it was not an issue, but a question about "how can I add it back"... just in case you knew. Thanks anyway.
