### ISSUE TITLE
Feature request: grey icon for nautilus

### ISSUE THREAD

**Issue by Th3Z0ne** [eti1337/arc-grey-theme#19]
Bonjour,

as of the latest Adawait icon theme update (which seems to be the backup theme) the icon for Nautilus has changed into this ugly (in my opinion) blueish drawer.

Is there a way to include the old icon into your theme or make a grey icon?

yours sincerely,
Th3Z0ne

**Comment by eti0** [comment]
Could you post a screenshot of the issue?
The theme shouldn't change any icons anyway.

**Comment by Th3Z0ne** [comment]
EDIT: sorry I feel really stupid now - you have it right on the front page which icon theme is used for apps. 
Thanks for you awsome work and sorry for stealing your time :( 

Hi! 
First of I know its not caused by your awesome theme (its the Adawait icon theme which seems to be used when ever there is no icon in your theme - am I right I hope) - I just have the hope you could fix it ^^
![nautilus_blue](https://cloud.githubusercontent.com/assets/8372908/26259729/9ac39788-3cca-11e7-900a-1b300fef7120.png)
That blue nautilus icon is bugging me - and I have the hope it could be fixed with your theme?

**Comment by eti0** [comment]
It's okay :)
Glad you found your solution
