### ISSUE TITLE
Color theme?

### ISSUE THREAD

**Issue by rawsh** [eti1337/arc-grey-theme#20]
Could you share the colors you use? I would like to customize some stuff myself, such as the terminal, slack, and atom. I'm most interested in the topbar color, I would like to blend slack in.

![screenshot from 2017-11-01 14-39-47](https://user-images.githubusercontent.com/7035671/32293882-87746df4-bf12-11e7-8391-a6eebdae4964.png)

**Comment by nthhhhhhh** [comment]
Looking at [gtk-dark.css](https://github.com/eti0/arc-grey-theme/blob/master/common/gtk-3.0/3.20/gtk-dark.css) the topbar color is #404040.

**Comment by eti0** [comment]
or you know.. you could use a colorpicker like the one that's in the GIMP.

ps: closing this as i don't see it as an "issue".
