### ISSUE TITLE
Chrome titlebar buttons

### ISSUE THREAD

**Issue by blzq** [eti1337/arc-grey-theme#22]
Titlebar buttons are too large in Chrome, see issue and fix in upstream

https://github.com/NicoHood/arc-theme/issues/62
https://github.com/NicoHood/arc-theme/commit/1eee9b816ff6f93c868f5568999d7dfcb542a11d

**Comment by eti0** [comment]
if you're willing to make a pull request i'll gladly accept it. :)

**Comment by blzq** [comment]
Seems to be fixed in the latest version of Chrome (67).
