### ISSUE TITLE
Transfer of ownership

### ISSUE THREAD

**Issue by pinpox** [eti1337/arc-grey-theme#23]
Hi, 
I see you don't maintain the theme anymore and would like to transfer it.
As I use it and would like to continue it I'm thinking about forking it or requesting that you transfer it.
Could you tell me what critical open issues there are you know of? What is the overall state of this? Would you transfer it to me or should I just fork it?

Cheers,
Pablo

**Comment by eti0** [comment]
hey.
there aren't any critical issues that i know of.
i've transferred the ownership to you. let me know if you still bump into any issues.
cheers

**Comment by pinpox** [comment]
Perfect thanks! Do you also maintain the AUR (linux arch package) I would change that to the new repo too.

**Comment by eti0** [comment]
no i don't manage the AUR repo so you'll have to contact the AUR repo owner for this to change.
