### ISSUE TITLE
Gnome 3.22 prompt gaps

### ISSUE THREAD

**Issue by ghost** [eti1337/arc-grey-theme#3]
When I try to logout/shutdown/restart the shell, I have a large gap between the text and the actual buttons. Currently running gnome on Arch.

**Comment by eti0** [comment]
I know about this issue and don't really know how to fix it.
If you have any idea where this comes from.
I'll gladly like to know.

**Comment by ghost** [comment]
Not all that familiar with github yet, but could you link this thread (and others) to @horst3180?

**Comment by eti0** [comment]
I don't think I can do that.
Maybe we can ask @horst3180 for help.

**Comment by hugupic** [comment]
dark-assets/misc/modal.svg is too short.
I would fix it but I'm not familiar with GitHub either, and apparently comments don't support .svg

**Comment by eti0** [comment]
@hugupic, could you host the file somewhere and send me a link ?
I'll replace it on the repo.

Thanks

**Comment by hugupic** [comment]
You can find it on my fork, https://github.com/hugupic/arc-grey-theme/blob/master/common/gnome-shell/3.18/dark-assets/misc/modal.svg  
I still need to check if the transparency matches the original because I quickly fixed it by changing the color of the parent arc-theme file.

**Comment by eti0** [comment]
Did you check the file ?
If the file is okay could you send me a PR ?

**Comment by hugupic** [comment]
So I just checked, the color and dimensions match, there's no color difference between the prompt and the button like in the original arc theme though.

**Comment by eti0** [comment]
Fixed with 12fdfe77daa1ba6f6e99d4b97107b8a60d72f5fa.
