### ISSUE TITLE
GTK2 buttons have shading

### ISSUE THREAD

**Issue by eti0** [eti1337/arc-grey-theme#4]
![2016-11-12-19 18 50](https://cloud.githubusercontent.com/assets/14180792/20239957/f7eaad9a-a90c-11e6-9ff0-f4c44e9dcdd5.png)

Having this issue is pretty dramatic, don't hesitate to comment if you found a fix.

**Comment by shef-er** [comment]
Same trouble.

**Comment by shef-er** [comment]
I think i found the reason of this trouble.
This is button resource from original arc theme
![button](https://cloud.githubusercontent.com/assets/3099409/20435666/1f0861f0-add7-11e6-8d46-b04aa9ebc084.png)

And this is from your rework
![button-grey](https://cloud.githubusercontent.com/assets/3099409/20435713/587290aa-add7-11e6-9aed-feebea23e1ed.png)
I think your version a bit blurry and there are bigger spaces at image sides.
The same trouble i found with scrollbars, and some other elements.

So, i've replaced recources from your theme with resorces from original arc theme, and now everything looks fine

**Comment by eti0** [comment]
Okay great.
Mind doing a pull request ?

**Comment by shef-er** [comment]
Sure, but i still working on recoloring them to grayscale

**Comment by eti0** [comment]
Hey, seems like I *finally* fixed the bug with 8cffe9a96e9759a1adbe5abf2209fcfe48a421b1.

![2016-11-27-22 32 27](https://cloud.githubusercontent.com/assets/14180792/20652002/66e07532-b4f1-11e6-9664-6396e8b97cf9.png)
