### ISSUE TITLE
Loading icon glitches

### ISSUE THREAD

**Issue by eti0** [eti1337/arc-grey-theme#5]
This issue doesn't occur on my system (gnome-shell 3.22.2).
But if you're having this issue too I'll look into it.

![screenshot from 2016-11-02 11-29-54](https://cloud.githubusercontent.com/assets/14180792/20239991/c5710da4-a90d-11e6-88d8-9c3a4a54a24f.png)

**Comment by ShellbackII** [comment]
Im experiences it on my laptop. Tried to reinstall the theme multiple times with same result.

I`m a somewhat neebie with just a little experience, don`t know exactly what information you need. But just ask and I will gladly help (love your flavor of the theme, except the glitch of course)

Some base information of my system:
Dell laptop
Intel i5
Intel grafic
Arch Linux
Gnome DE

**Comment by Th3Z0ne** [comment]
I have had it on my system (gnome shell 3.22.3 as well) - the fix was that I found a "process-working.svg" that is much more granular as the one that comes by default. (sadly I do not remember which theme I found it on)
Oh svg can not be uploaded .... so here we go.... in the ZIP is the ..svg that is working for me
[process-working.svg.ZIP.zip](https://github.com/eti0/arc-grey-theme/files/949648/process-working.svg.ZIP.zip)

**Comment by ShellbackII** [comment]
That did the trick!

Thank you very much!!!

For the record, I'm using the dark variant. I haven't tried if the other variants experiences the same problem, but if they do, it should only be to replace the same svg file.

**Comment by eti0** [comment]
Alright, if you guys could confirm that the issue has disappeared with the latest update that'd be nice.
If everything is working fine I'll just close the issue.

**Comment by Th3Z0ne** [comment]
I did pull master and it stayed the same for me - as its a common resource it is the same for Arc-Grey, Arc-Grey-Darker and Arc-Grey-Dark =)

Ps, thanks for maintaining that great theme - I am really proud right now, my first valuable contribution to something open source that I use ^^

**Comment by ShellbackII** [comment]
well... I uninstalled it and installed it again from here... but unfortuantly, same glitch...

Strange since it was fixed when I manually switched the file.

**Comment by Th3Z0ne** [comment]
@ShellbackII what file ended up on disk in `/usr/share/themes/Arc-Grey-[your version]/gnome-shell/common-assets/misc/process-working.svg` maybe we (I) have to fix it for each version? (normal, dark, and darker mhmm) 

Which shell theme do you use (normal, darker or dark)?

**Comment by Th3Z0ne** [comment]
Did another commit #17  this time to the process-working.svg in the 3.18 folder structure as all above (3.20, 3.22) are symlinks to 3.18 ... whereas my previous commit was for 3.16 - did it in the wrong version - my bad, sorry for that.

**Comment by eti0** [comment]
No problem, it's really nice having people fixing my stuff when I don't have the time to!

Also, same thing as before, if you guys could confirm that everything is fine I'll just close the issue ticket. :)

**Comment by ShellbackII** [comment]
now it work out of the box!

**Comment by Th3Z0ne** [comment]
Yay =D great - love the color scheme a lot

**Comment by eti0** [comment]
Okay, great!

Thanks a lot to both of you :+1:
