### ISSUE TITLE
Blue color left in Chrome apps

### ISSUE THREAD

**Issue by steffen678** [eti1337/arc-grey-theme#6]
In every Chrome app, there is still some blue color left. For example, the background color in a new tab or the background of the tab bar. 
![screenshot from 2016-11-16 11-15-47](https://cloud.githubusercontent.com/assets/1119538/20343300/15518212-abee-11e6-9a03-17f360ce8ffd.png)
![screenshot from 2016-11-16 11-15-32](https://cloud.githubusercontent.com/assets/1119538/20343301/1553b9ec-abee-11e6-9768-568e21fdff8e.png)

**Comment by eti0** [comment]
Fixed in #7

**Comment by steffen678** [comment]
This has to be some kind of issue with the Gtk2 theme, too, I guess, because if you aren't using the Chrome theme, the blue background is still there. 
![screenshot from 2016-11-16 14-17-54](https://cloud.githubusercontent.com/assets/1119538/20348777/836a058a-ac07-11e6-82b0-005bc0b4793e.png)

**Comment by eti0** [comment]
Whoops, not intended, I think I can change that.
I'll see what I can do later since I'm at work right now.
