### ISSUE TITLE
Cinnamon 3.2 Support

### ISSUE THREAD

**Issue by ghost** [eti1337/arc-grey-theme#8]
Horst updated arc to support Cinnamon 3.2 here:

https://github.com/horst3180/arc-theme/commit/15699330e7e271f33f7f3e3c29c901acc3c36c89

Could you please add the fixes to your theme as well?

**Comment by eti0** [comment]
Support has been added with 465ddecde0b9dbf035b66cca7c0b3b56b60b769b.  
Please clone the dev branch and if there aren't any issues I'll merge the branch with master.

**Comment by eti0** [comment]
Update:
Merged the dev branch with master with b3b43810a93a09a7148b4a0c95cd62836b055154.
