### ISSUE TITLE
Pinky close button wanna be light-grey?

### ISSUE THREAD

**Issue by ghost** [eti1337/arc-grey-theme#9]
Hi! Thank you for that gorgeous adaptation of Arc Theme. I really like it monochromed! 
But we have a pinky close button. Maybe you can convert it to BW pallette for grey theme style? 
Thanks!

**Comment by eti0** [comment]
The only thing that really got me bored of Arc was the blue in the first place.
The red brings a little more style to the theme so I'm just going to let it be for now.

You can always try changing it yourself (it really isn't that hard).
Just edit `common/gnome-shell/3.*/assets.svg` and regenerate them by using `./render-assets.sh` from the working directory.
See [hacking.md](https://github.com/eti0/arc-grey-theme/blob/master/HACKING.md) if you want to learn more.

Have fun ! 💯 🔥

**Comment by blzq** [comment]
Might be worth noting that the close button on XFWM window bars is grey instead of red both when active and inactive (is it supposed to be red when active like GTK?)
